version: '3.7'

networks:
  gis-net:
    driver: bridge

services:

  test:
    image: ghcr.io/datakaveri/gis-test:latest
    environment:
      - RS_URL=https://rs.iudx.org.in
      - LOG_LEVEL=INFO
      - GIS_JAVA_OPTS=-Xmx1024m
    volumes:
      - /home/ubuntu/configs/gis-config-test.json:/usr/share/app/configs/config-test.json
      - /home/ubuntu/configs/keystore-gis.jks:/usr/share/app/configs/keystore_old.jks
      - ./docker/runTests.sh:/usr/share/app/docker/runTests.sh
      - ./src/:/usr/share/app/src
      - ${WORKSPACE}:/tmp/test
    networks:
      - gis-net
    logging:
         driver: "json-file"
         options:
             max-file: "5"
             max-size: "100m"
    command: bash -c "docker/runTests.sh"

  integTest:
    image: ghcr.io/datakaveri/gis-test:latest
    environment:
      - RS_URL=https://rs.iudx.org.in
      - LOG_LEVEL=INFO
      - GIS_JAVA_OPTS=-Xmx1024m
    volumes:
      - /home/ubuntu/configs/gis-config-test.json:/usr/share/app/configs/config-dev.json
      - /home/ubuntu/configs/keystore-gis.jks:/usr/share/app/configs/keystore_old.jks
      - ./src/:/usr/share/app/src
    ports:
      - "8443:8443"
    networks: 
      - gis-net
    logging:
         driver: "json-file"
         options:
             max-file: "5"
             max-size: "100m"
    command: bash -c "mvn clean compile exec:java@gis-server"
